version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1
    ports:
      - "9002:9000"
      - "8123:8123"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse_password

    restart: always

  object-store:
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z
    environment:
      - MINIO_ROOT_USER=minio-user
      - MINIO_ROOT_PASSWORD=minio-password
    volumes:
      - minio-data:/data
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  minio-data:
    driver: local